#!/usr/bin/env node

const path = require('path');
const shell = require('shelljs');

const outputPath = path.resolve(__dirname, '../sailfish-ui');
shell.rm('-rf', outputPath);
shell.cp('-r', path.resolve(__dirname, 'static'), outputPath);

const configPath = path.resolve(__dirname, 'vusion.config.js');
shell.exec(`vusion build -c "${configPath}" -t default`);
