#!/usr/bin/env node

const path = require('path');
const shell = require('shelljs');

const theme = 'default';

const outputPath = path.resolve(__dirname, '../sailfish-ui');
shell.rm('-rf', outputPath);
shell.cp('-r', path.resolve(__dirname, 'static'), outputPath);

const configPath = path.resolve(__dirname, 'vusion.config.js');
const cmd = `vusion dev -p 9002 -c "${configPath}" -t ${theme}`;
console.info(cmd);
shell.exec(cmd);
